language: python
sudo: false
cache:
  - apt
  - bundler
  - pip
matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 2.7
    env: TOXENV=style
  - python: 2.7
    env: TOXENV=docs
addons:
  apt:
    sources:
    - heroku
    packages:
    - pandoc
    - enchant
    - heroku-toolbelt
    - redis-server
services:
  - redis-server
before_install:
- rvm install 2.1.5
- pip install --upgrade setuptools pip wheel
install:
- pip install tox==2.6.0
- gem install danger
- gem install danger-commit_lint
- gem install chandler
before_script:
- bundle exec danger
- createdb dallinger -U postgres
env:
  global:
  - DATABASE_URL=postgresql://postgres@localhost/dallinger
  - PORT=5000
  - secure: isabc6zJWlMBizW/5MbjmWJ9Q2shDj0rjTPmtQmq7QZrrmxczjWfgiQE0i6tcw3wPvBIOgsA4M806ddgM/oeUPWt892BlPHUESb7j96zHtig9B/P4kwH11EPK4pEPcvg90NfVeDCqYHVSNcMtsRTSf93Fg7aT081URb7vRUykxg=
  - secure: rWBAifHvKlQabe6gvz+edMEtjtDnpwI4RFHJB1ytYSNVKQ59s7fIk2q39IZc8K3Uix7ZtP3G7ws6ufQhOj44Pm4j1J+rbLnDjdMtmcDN5aiSnwb05JpltZXCNjUqAu/CBFZ44lnNenZp4uSLhU/kLVhB2Q+UPvyWNFgApEVoiHM=
  - secure: fd4hFOH60UV8laBN4Mjva0w/EmVK3SVC5p/0O1oqPriPhUpoJ3eVVRvITbdvPctEJJgRR9t62rPk+Rv4EOXeRFfsjZK9gOfQqv/9VhJBebdQfOx2dwQLjDiGTrklkokDIDyfpyYOoJzZ/oP+6EneD403ilHnXC4fd/4EDQmaIRI=
  - secure: 3rnkGugv5Hp71gjwQMUj5tup7/xk94p5IXEh0VItSXTziKn0pBY+yrCzAuIzlylbrl0baLaZOFGEFn2K+Jf+tr9mmN23X+zOUNsIqC4swlLLJx6hzH5AZaRmqzGjURM2gLISUayXGT9flOXyOKzzCGFELJKG9KlVyEOJ4fk04wQ=
script:
- tox
after_success:
- bash <(curl -s https://codecov.io/bash)
- if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    sh scripts/github_releases.sh;
  fi
before_deploy:
- pandoc --from=markdown --to=rst --output=README.rst README.md
deploy:
  - provider: pypi  # test pypi
    distributions: sdist
    server: https://testpypi.python.org/pypi
    user: "suchow"
    password:
      secure: "A8nIC9tLyVV1X5020JbJwpBCSS7kQvuXP2pLIgu40CPB/ZfU3OOC5IyjfFWypIP/CCExM8o6Spb5UJccgLLUy7OLGMPaO/8Ne7BCyh75uvav5iX4KlP/j8eWih+CPGWPhO4pYsXnzpGi+GSQnwmhxdoPmllUbyLvmppsfI+vBf9pYGRpF8BgjIt0S3ffYRh030S6jFSQ1HCEz/JDIaHn4eh+nn/squVXKHMbejR8IaMnVc+Xus8mT7yzQhdIWn/jCV7GCq1uvBU1Jieh9lR18ohwT3FE51rnPZvVEGUmW0JaWmVYjwKRevXPfS9gbDSGBOAwMypVk5lPSoJlXhUpfuUEEbWvl/XpO+B9C3VGgtFSR3R+9zN7Vhg89FkVjxBIEVV6t5p+7RRtKYkyp08T9B72wzwG8Xq2XMFNb9/w1hJsx5YuZZVLQOHJlae64jstJOzAiQUXN0ZAsSU6lyH2MXJPLhgqc8Lfd05/5swnkrbj/PxchawbwwnmLps9DlyVVcxH8XdW3n8NYU4tzc+2NwM0/+AMhQQ7hQ5YTz1YSDiHNUTmFqFoawUzeDUT+5NDfy+DYk8SkIj8i6gWsEES1fPkckTvsuKrJUEy781Ff5dl/nb8xsX8UC3DhcEqYkYkr+3bgmKydMCOGGB9k+/2/p0AS67Rmu+/Vs5op6jGhp8="
    on:
      condition: $TRAVIS_PYTHON_VERSION = "2.7"
    skip_cleanup: true
  - provider: pypi  # production pypi
    distributions: sdist
    user: "suchow"
    password:
      secure: "A8nIC9tLyVV1X5020JbJwpBCSS7kQvuXP2pLIgu40CPB/ZfU3OOC5IyjfFWypIP/CCExM8o6Spb5UJccgLLUy7OLGMPaO/8Ne7BCyh75uvav5iX4KlP/j8eWih+CPGWPhO4pYsXnzpGi+GSQnwmhxdoPmllUbyLvmppsfI+vBf9pYGRpF8BgjIt0S3ffYRh030S6jFSQ1HCEz/JDIaHn4eh+nn/squVXKHMbejR8IaMnVc+Xus8mT7yzQhdIWn/jCV7GCq1uvBU1Jieh9lR18ohwT3FE51rnPZvVEGUmW0JaWmVYjwKRevXPfS9gbDSGBOAwMypVk5lPSoJlXhUpfuUEEbWvl/XpO+B9C3VGgtFSR3R+9zN7Vhg89FkVjxBIEVV6t5p+7RRtKYkyp08T9B72wzwG8Xq2XMFNb9/w1hJsx5YuZZVLQOHJlae64jstJOzAiQUXN0ZAsSU6lyH2MXJPLhgqc8Lfd05/5swnkrbj/PxchawbwwnmLps9DlyVVcxH8XdW3n8NYU4tzc+2NwM0/+AMhQQ7hQ5YTz1YSDiHNUTmFqFoawUzeDUT+5NDfy+DYk8SkIj8i6gWsEES1fPkckTvsuKrJUEy781Ff5dl/nb8xsX8UC3DhcEqYkYkr+3bgmKydMCOGGB9k+/2/p0AS67Rmu+/Vs5op6jGhp8="
    on:
      branch: master
      tags: true
      condition: $TRAVIS_PYTHON_VERSION = "2.7"
    skip_cleanup: true
