environment:
  # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
  # /E:ON and /V:ON options are not enabled in the batch script intepreter
  # See: http://stackoverflow.com/a/13751649/163740
  CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"
  TOX_ENV: "pywin"
  DATABASE_URL: postgresql://postgres@localhost/db
  PORT: 5000
  aws_access_key_id: 
    secure: FIX ME
  aws_secret_access_key:
    secure: FIX ME
  mturk_worker_id:
    secure: FIX ME

  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "32"

build: false

branches:
  only:
  - windows

install:
  - ps: "wget https://github.com/cloudify-cosmo/appveyor-utils/archive/master.zip -OutFile ./master.zip"
  - "7z e master.zip */appveyor/* -oappveyor"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - pip install -r requirements.txt

build_script:
  - python setup.py install

before_test:
  - "%CMD_IN_ENV% pip install tox"

test_script:
  - "%CMD_IN_ENV% tox -e %TOX_ENV%"
